name: "top repo action"
description: "Create a markdown table in README.md with the top repositories of your GitHub account."
author: "tot0p"
branding:
  icon: "star"
  color: "blue"

inputs:
  username:
    description: "GitHub username"
    required: true
  include_org_repos:
    description: "Include organization repositories"
    required: false
    default: false
  name_of_balise:
    description: "Name of the balise"
    required: false
    default: "Top-Repositories"
  commit_message:
    description: "Commit message"
    required: false
    default: "Update README.md with top repositories"
  top:
    description: "Number of top repositories"
    required: false
    default: 3

runs:
  using : "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: run python
      shell: bash
      run: |
        python src/main.py
      env :
        USERNAME: ${{ inputs.USERNAME }}
        INCLUDE_ORG_REPOS: ${{ inputs.INCLUDE_ORG_REPOS }}
        NAME_OF_BALISE: ${{ inputs.NAME_OF_BALISE }}
        COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
        TOP: ${{ inputs.TOP }}